version: '3'
services:
  web: 
    image: dievri/croco
    volumes:
      - ./configs:/etc/nginx/conf.d
      - ./tmp:/tmp
    ports:    
      - "8080:80"
      - 5000
  redis: 
    image: "redis:alpine"
    hostname: "redis"
    command: ["redis-server", "--appendonly", "yes"]
    volumes: 
      - ./data:/data
